channels:
- defaults
- conda-forge
dependencies:
- holidays=0.29
- ipykernel=6.25.0
- jinja2=3.1.2
- matplotlib=3.8.0
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.1.1
- python=3.11.5
- pyyaml=6.0.1
- scikit-learn=1.2.2
- seaborn=0.12.2
- statsmodels=0.14.0
- xgboost=1.7.3
name: int-proyeccion
