channels:
- defaults
- conda-forge
dependencies:
- ipykernel=6.26.0
- matplotlib=3.7.2
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.1.1
- python=3.11.5
- pyyaml=6.0.1
- seaborn=0.12.2
name: int-proyeccion
