channels:
- defaults
- conda-forge
dependencies:
- holidays=0.29
- ipykernel=6.25.0
- jinja2=3.1.2
- matplotlib=3.8.0
- numpy=1.26.0
- openpyxl=3.0.10
- pandas=2.1.1
- pmdarima=2.0.3
- prophet=1.1.4
- python=3.11.5
- pyyaml=6.0.1
- scikit-learn=1.2.2
- seaborn=0.12.2
- statsmodels=0.14.0
- xgboost=1.7.3
- pip:
  - absl-py==2.0.0
  - astunparse==1.6.3
  - cachetools==5.3.2
  - certifi==2023.11.17
  - charset-normalizer==3.3.2
  - flatbuffers==23.5.26
  - gast==0.5.4
  - google-auth==2.23.4
  - google-auth-oauthlib==1.1.0
  - google-pasta==0.2.0
  - grpcio==1.59.3
  - h5py==3.10.0
  - idna==3.4
  - keras==2.15.0
  - libclang==16.0.6
  - markdown==3.5.1
  - ml-dtypes==0.2.0
  - oauthlib==3.2.2
  - opt-einsum==3.3.0
  - protobuf==4.23.4
  - pyasn1==0.5.1
  - pyasn1-modules==0.3.0
  - requests==2.31.0
  - requests-oauthlib==1.3.1
  - rsa==4.9
  - scikeras==0.12.0
  - tensorboard==2.15.1
  - tensorboard-data-server==0.7.2
  - tensorflow==2.15.0
  - tensorflow-estimator==2.15.0
  - tensorflow-intel==2.15.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - termcolor==2.3.0
  - typing-extensions==4.8.0
  - werkzeug==3.0.1
  - wrapt==1.14.1
name: int-proyeccion
